### ISSUE TITLE
Unresponsive Login button

### ISSUE THREAD

**Issue by DaveSladeSewbrec** [NERC-CEH/lerc-wales-app#11]
**Describe the issue**
The App doesn't seem to respond to the sign in button, and doesn't provide any kind of feedback. Brad can't get it to work at all, and I have to hit the sign in button two or three times in very quick succession for it to submit the form. When it does submit, the only feedback I get is "incorrect email or password", regardless of what I enter into the username or email forms.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Should either sign you in or provide an error message.

**Screenshots**
If applicable, add screenshots to help explain your problem. Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Smartphone (please complete the following information):**
I don't know versions of Android Brad phone's are running (he's seeing the same behaviour on work and personal phones), but mine is based on Android 12.

**Additional context**
Information provided by Berwyn Powell (berwyn@bis.org.uk).

**Comment by kazlauskis** [comment]
@DaveSladeSewbrec does it work if you tap on the button corner or side? Also, something similar was fixed in the iRecord App a while ago, any chance they could try it out and tell us if the button works there?

**Comment by robin-hutchinson** [comment]
A similar issue described by another user:

Issue Description: Unable to log in - I tried to submit a record and had a new login request which took me to I record. I had to reset password but it wouldn’t let me in

Expected Behaviour: The Username/Email and password from iRecord allow log in on the LERC Wales app.

Steps to Reproduce:

Date/Time Issue Observed (when did you first notice the issue, provide a specific date if possible, and last known occurrence): 05 June 2025, on going. Has reset the password to iRecord but this did not resolve the issue, and did on laptop not mobile phone. Would this make a difference. I have tried to reset password agains but nothing happens when press reset button

Frequency of the Issue (is it consistent or intermittent): Consistent

App Version (which version of the app are you using, check in the app settings or app store):6.1.2

Device (what phone or tablet are you using, include model and brand): Galaxy A35 5G 

Android 15
Operating System Version (The Android or iOS version running on your device):

System Update Status (are any pending Android/iOS updates): Not that I can tell 
says phone updated last on 6 June 2025

Available Device Storage (how much free storage space does your device currently have):102gb, 1.7gb of memory

**Comment by robin-hutchinson** [comment]
An update: "having read the other report [above] I repeated the same experience for login to get same error message for login details and repeatly pressed to reset password to get a new log in. I did the login from my mobile phone and it now appears to work and I submitted a record."

**Comment by DaveSladeSewbrec** [comment]
Apologies for the delay in responding - I'd not noticed the question. On Friday Adam and I struggled to log into a Samsung Tablet (Galaxy Tab A9+, running Android 15). I'm still not sure what it was that worked and what did not. It took me about 20 attempts (Adam had completely failed) but eventually I managed to sign in. Trying now in the office with your suggestion above I can see that it is the centre of the button that is unresponsive, and tapping off centre does seem to work.

**Comment by robin-hutchinson** [comment]
As an update on this issue, the app appears to be logging users back out so they need to sign in again to submit a new record (rather than staying logged in to the app), then having difficulty logging in again. 

This is on a Galaxy A35 5G, Android 15, with 102gb, 1.7gb of memory, with the error happening today.
